- Added A test csv response from postgres
buerokratt/Analytics-Module pull request #27
Opened 2023-01-11 14:37 UTC by 1AhmedYasser

- Added a ruuter header to treat the response as a downloadable file

2023-01-12 08:58 UTC, gdrui requested changes

2023-01-12 08:58 UTC, gdrui commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
I think this endpoint should already take in a parameter and use that to determine which query to run. For example here `test-csv-response` could be sent as a parameter to the ruuter query, so this PR would already expose the full API the way it should be used in the future.

2023-01-12 10:14 UTC, 1AhmedYasser commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
Yes your right, noted, will make the appropriate changes

2023-01-12 13:27 UTC, 1AhmedYasser commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
I tried adding this 

```
get_message:
  call: http.post
  args:
    url: "http://resql:8082/{path}"
  query:
    path: "testing" 
  result: message

return_value:
  return: ${message}
```

And also tried Adding this

```
assign_step:
  assign:
    path: "testing"

get_message:
  call: http.post
  args:
    url: http://resql:8082/${path}
  result: message

return_value:
  return: ${message}
```

And i tried other scenarios, but it always responds with 

java.lang.IllegalArgumentException: Not enough variable values available to expand 'path'

Any ideas on how to solve this from rutter side ?

2023-01-12 14:33 UTC, gdrui commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
It looks like the query parameters are exposed inside `incoming.params` so for `?path=data` it would be  `${incoming.params.path}`

However as far as I can tell none of the variables are usable in the url field of these requests, is this correct @turnerrainer? Maybe this is something that might be added to Ruuter in the future, since these variables could be compiled before sending it to the HTTP request.

We probably need another solution. For example we could have a pre-defined list of possible queries and based on the parameter we use one or the other.

2023-01-16 11:22 UTC, gdrui approved these changes

2023-01-18 06:27 UTC, turnerrainer reviewed
Please add newline at the end of file.

2023-01-18 06:27 UTC, turnerrainer commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
> For example we could have a pre-defined list of possible queries and based on the parameter we use one or the other.

@gdrui this is the solution throughout everything we do. Dynamic queries based on input provided within the request is a no go. If you provide time period as part of a request body, then sure, that's fine, but that's pretty much it. We want both Ruuter and Ressql services to be as rigid as possible - just an endpoint with minimal possibility to manipulate with query parameters.

2023-01-18 06:27 UTC, turnerrainer commented on DSL/Ruuter/GET/get-csv.yml
> +    url: http://resql:8082/test-csv-response
> However as far as I can tell none of the variables are usable in the url field of these requests, is this correct @turnerrainer? Maybe this is something that might be added to Ruuter in the future, since these variables could be compiled before sending it to the HTTP request.

This seems to be a missing feature of Ruuter, we'll add it to our backlog. But we won't use it here.

2023-02-07 11:29 UTC, gdrui approved these changes

2023-02-07 11:32 UTC, merged