Initialize new React app
buerokratt/Analytics-Module pull request #28
Opened 2023-01-11 21:04 UTC by baha-a

Initialize a new React app into GUI folder

2023-01-13 09:01 UTC, gdrui requested changes

2023-01-16 00:01 UTC, baha-a commented on docker-compose.yml
> +      - REACT_APP_BASE_URL=http://localhost:8080
This url will be called from the browser, not from the container itself. So it won't work if we used `ruuter` here.

2023-01-16 00:08 UTC, baha-a commented on README.md
> +    - Add "https://localhost:3000" to `allowedOrigins` array:
I'm not able to make it works this way. Ruuter never picks it up  for some reason (I've tried to add `ruuter.cors.allowedOrigins` as environment to `docker-compose.yml`). Should I change something from the Ruuter project ?

2023-01-16 00:10 UTC, baha-a commented on GUI/.prettierrc
> +}
Done.

2023-01-16 07:42 UTC, gdrui commented on docker-compose.yml
> +      - REACT_APP_BASE_URL=http://localhost:8080
Good point

2023-01-16 08:48 UTC, gdrui commented on README.md
> +    - Add "https://localhost:3000" to `allowedOrigins` array:
It looks like the correct env variable is  - application.cors.allowedOrigins=http://localhost:3000
It worked for me. You have to remove the existing container, otherwise the changed env variable wont be applied

2023-01-16 10:57 UTC, baha-a commented on README.md
> +    - Add "https://localhost:3000" to `allowedOrigins` array:
Worked for me too. You are correct, I had to remove the ruuter container first.

2023-01-16 11:21 UTC, gdrui approved these changes

2023-01-17 11:11 UTC, merged