23 Resql endpoints for chat metrics
buerokratt/Analytics-Module pull request #30
Opened 2023-01-17 07:51 UTC by gdrui

2023-01-18 06:19 UTC, turnerrainer reviewed
Please add newlines at end of files.

2023-01-19 11:50 UTC, baha-a requested changes

2023-01-19 11:50 UTC, baha-a commented on DSL/Resql/get-chat-count-total.sql
> +SELECT COUNT(distinct base_id)
Please change `distinct` to all upper case.

2023-01-19 11:50 UTC, baha-a commented on DSL/Resql/get-avg-waiting-time.sql
> +SELECT avg(
Please change `avg` to all upper case.

2023-01-20 07:16 UTC, gdrui commented on DSL/Resql/get-avg-messages.sql
> +SELECT AVG(num_messages)
Very good point, I'll wrap these with COALESCE, its shorter

2023-01-20 07:29 UTC, gdrui commented on DSL/Resql/get-pct-correctly-understood.sql
> +            )::numeric / COUNT(*)::numeric
Good point

2023-01-20 12:34 UTC, baha-a approved these changes

2023-01-23 06:25 UTC, merged