18 Ruuter DSL `Feedback/negative`
buerokratt/Analytics-Module pull request #31
Opened 2023-01-18 07:22 UTC by baha-a

2023-01-18 08:18 UTC, 1AhmedYasser commented on DSL/Resql/negative-feedback.sql
> +WHERE feedback_rating <= 5
As i worked with their test db environment, i added a couple of checks just to make sure i get the right response here
1) Make Sure the chat status is closed to avoid any wrong data of feedback in an open chat
2) Make Sure that the feedback_rating is not null in case a user skipped the rating
3) Make Sure that you cast feedback_rating to int as i found for some reason they have the feedback_rating column as VARCHAR so to avoid any miscast here

So i would to to suggest adding these changes as well
```
SELECT base_id AS chat_id
FROM chat
WHERE feedback_rating IS NOT NULL
AND status = 'ENDED'
AND feedback_rating::int <= 5
```
Thank you

2023-01-18 09:31 UTC, baha-a commented on DSL/Resql/negative-feedback.sql
> +WHERE feedback_rating <= 5
Fixed.

2023-01-18 09:42 UTC, 1AhmedYasser commented on DSL/Resql/negative-feedback.sql
> +WHERE feedback_rating <= 5
Thank you

2023-01-18 11:39 UTC, gdrui requested changes

2023-01-18 12:25 UTC, baha-a commented
Please note that `cookie` has been renamed to `token`.

2023-01-19 08:56 UTC, gdrui approved these changes

2023-01-23 07:13 UTC, merged