8 Metrics and graphics under menu button Bürokratt
buerokratt/Analytics-Module pull request #36
Opened 2023-01-23 07:51 UTC by baha-a

2023-01-24 08:56 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/avg-session-length-client-left.yml
> +extractRequestData:
Add Parameter validation here as well

2023-01-24 08:56 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/avg-session-length-csa.yml
> +extractRequestData:
Add Parameter validation here as well

2023-01-24 08:56 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/avg-session-length-no-csa.yml
> +extractRequestData:
Add Parameter validation here as well

2023-01-24 08:56 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/pct-currectly-understood.yml
> +extractRequestData:
Add Parameter validation here as well

2023-01-24 08:57 UTC, 1AhmedYasser submitted a review, later dismissed
Add Parameters Validation

2023-01-24 14:26 UTC, gdrui requested changes
The DSL here is not what is required by the issue, the query should be composed based on the metric, additional options and time period and the result should be a dataset grouped by day or hour, so it could be rendered as a chart. 

Also, lets start keeping Ruuter yml files in the folder that reflects which tab they belong to, in this case `buerokratt`.

Another note is that you could probably have one Ruuter endpoint to handle all the different options and have that retrieve the data from a specific Resql endpoint.

2023-01-24 16:34 UTC, 1AhmedYasser commented
> Also, lets start keeping Ruuter yml files in the folder that reflects which tab they belong to, in this case `buerokratt`.

Yup Should Also modify the dsl to handle all 5 period options as follows for example

```
SELECT date_trunc(:metric, created) AS date_time,
       COUNT(DISTINCT base_id)
FROM chat
WHERE EXISTS
    (SELECT 1
     FROM message
     WHERE message.chat_base_id = chat.base_id
       AND message.author_role = 'backoffice-user')
  AND EXISTS
    (SELECT 1
     FROM message
     WHERE message.chat_base_id = chat.base_id
       AND message.author_role = 'end-user')
  AND created::date BETWEEN :start::date AND :end::date
GROUP BY 1
```

2023-01-30 10:43 UTC, gdrui requested changes

2023-01-30 10:43 UTC, gdrui commented on DSL/Resql/byk-avg-response-speed.sql
> +    JOIN chat c ON m.chat_base_id = c.base_id
you dont actually use `chat` in this query

2023-01-30 10:43 UTC, gdrui commented on DSL/Resql/byk-avg-response-speed.sql
> +            SELECT MIN(created)
hmm, don't you mean the `MAX(created)` to get the latest message before the chat's message?

2023-01-30 10:43 UTC, gdrui commented on DSL/Resql/byk-avg-sessions-time-customer.sql
> +    WHERE chat.status IN ('ANSWERED', 'CLIENT-LEFT')
AFAIK these are not values in chat.status but values in message.event, so these should be chats that have any messages with these events.

2023-01-30 10:43 UTC, gdrui commented on DSL/Ruuter/GET/buerokratt/byk-avg-sessions-time.yml
> +    - condition: ${options.includes('byk')}
this is a clever way to combine multiple options, even though Ruuter makes the readability a little difficult

2023-02-01 04:03 UTC, baha-a commented on DSL/Resql/byk-avg-response-speed.sql
> +            SELECT MIN(created)
You are right, it should be `MAX`.
Fixed.

2023-02-01 05:24 UTC, baha-a commented on DSL/Resql/byk-avg-sessions-time-customer.sql
> +    WHERE chat.status IN ('ANSWERED', 'CLIENT-LEFT')
Fixed

2023-02-01 05:25 UTC, baha-a commented on DSL/Resql/byk-avg-response-speed.sql
> +    JOIN chat c ON m.chat_base_id = c.base_id
Fixed

2023-02-01 07:12 UTC, baha-a commented
For the intents metrics, I assumed that there is a table called `intents` connected with table `message` by `message.intent_base_id`.

2023-02-01 07:55 UTC, gdrui approved these changes

2023-02-17 11:21 UTC, closed without merging