9-metrics-and-charts-under-menu-button-tagasiside-feedback
buerokratt/Analytics-Module pull request #38
Opened 2023-01-24 23:37 UTC by 1AhmedYasser

2023-01-30 11:22 UTC, gdrui requested changes

2023-01-30 11:22 UTC, gdrui commented on DSL/Resql/feedback-avg-feedback-to-buerokratt-chats.sql
> +       AND message.author_role = 'buerokratt')
the author_role for the chatbot is actually `chatbot`.
`buerokratt` is used in place of automated messages like greetings and for logging events

2023-01-30 13:52 UTC, baha-a requested changes

2023-01-30 13:52 UTC, baha-a commented on DSL/Resql/feedback-chats-with-negative-feedback.sql
> +GROUP BY 1
Please replace `GROUP BY 1` with `GROUP BY date_time` for better readability and to avoid confusion when someone else reads the code.

2023-01-30 13:52 UTC, baha-a commented on DSL/Resql/feedback-avg-feedback-to-buerokratt-chats.sql
> +GROUP BY 1
Please replace `GROUP BY 1` with `GROUP BY date_time` for better readability and to avoid confusion when someone else reads the code.

2023-01-30 13:52 UTC, baha-a commented on DSL/Resql/feedback-csa-chats-feedback-nps.sql
> +ORDER BY 1
Please replace `GROUP BY 1` with `GROUP BY date_time` and `ORDER BY 1` with `ORDER BY date_time` for better readability and to avoid confusion when someone else reads the code.

2023-01-30 13:52 UTC, baha-a commented on DSL/Resql/feedback-selected-csa-feedback-nps.sql
> +ORDER BY 1
For better readability and to avoid confusion when someone else reads the code, please replace:
- `GROUP BY 1, 2, 3` with `GROUP BY date_time, customer_support_id, customer_support_display_name`
- `ORDER BY 1` with `ORDER BY date_time`

2023-01-30 13:52 UTC, baha-a commented on DSL/Resql/status-all-chats.sql
> +  AND message.event IN (:events)
I assume that `:events` could have multiple values here.
If my assumption is true and If there are multiple rows in the message table with the same `chat_base_id` but different values of `event` then this query may not return the expected results since `DISTINCT` clause only applies to `chat.base_id`.

2023-01-31 20:27 UTC, 1AhmedYasser commented on DSL/Resql/status-csa-chats.sql
> +  AND message.event in (:events)
Yes your assumption here is correct, however a single chat can have multiple events happening inside it, so for example a single chat may have a `request-authentication` event and a `client-left` event, thats why in this query i am putting distinct on chat.base_id , date_time & event all together

2023-01-31 20:27 UTC, 1AhmedYasser commented on DSL/Resql/status-all-chats.sql
> +  AND message.event IN (:events)
Yes your assumption here is correct, however a single chat can have multiple events happening inside it, so for example a single chat may have a request-authentication event and a client-left event, thats why in this query i am putting distinct on chat.base_id , date_time & event all together

2023-02-01 02:07 UTC, baha-a commented on DSL/Resql/status-csa-chats.sql
> +  AND message.event in (:events)
Okay, so result such as the following are expected:

| chat.base_id |  date_time  |  message.event  | 
|---|---|---|
| 1  | _some date1_  |  event1 | 
| 1  | _some date2_  |  event2 | 
| 2  | _some date3_  |  event1 |
| 2  | _some date4_  |  event2 |

2023-02-01 02:08 UTC, baha-a approved these changes

2023-02-01 02:16 UTC, 1AhmedYasser commented on DSL/Resql/status-csa-chats.sql
> +  AND message.event in (:events)
Exactly 👌

2023-02-01 07:47 UTC, gdrui approved these changes

2023-02-02 08:45 UTC, gdrui requested changes

2023-02-02 08:45 UTC, gdrui commented on DSL/Resql/status-all-chats.sql
> +SELECT DISTINCT chat.base_id,
Looks like this was supposed to return the count of chats per each status, currently it just returns a list of chats and statuses

2023-02-02 08:45 UTC, gdrui commented on DSL/Resql/status-csa-chats.sql
> +SELECT DISTINCT chat.base_id,
Same situation here

2023-02-02 11:04 UTC, gdrui approved these changes

2023-02-10 08:25 UTC, closed without merging