7 Metrics and graphics under menu button Vestlused (chats)
buerokratt/Analytics-Module pull request #41
Opened 2023-01-27 00:09 UTC by baha-a

2023-01-27 16:04 UTC, 1AhmedYasser commented on DSL/Resql/chat-avg-duration.sql
> +    AND message.created BETWEEN :start::timestamptz AND :end::timestamptz
Please Use `WHERE created::date BETWEEN :start::date AND :end::date` as dates not as timestamps, to avoid time collision, for example if you specify 1 day and added the period as day it will return and empty result because of the time collision, please unify this in all your queries

2023-01-30 11:45 UTC, gdrui requested changes

2023-01-30 11:45 UTC, gdrui commented on DSL/Resql/chat-cif-all-csas-away.sql
> +AND csa.status = 'AWAY'
I think you will need to check if the status was AWAY during these particular chats as well? Otherwise the CSA might have just been away once at some unrelated point of time and this would still match.

2023-01-30 11:45 UTC, gdrui commented on DSL/Resql/chat-cif-long-waiting-time.sql
> +            MIN(created) FILTER (WHERE event = 'contact-information-fulfilled')
AFAIK `contact-information-fulfilled` is not related to the waiting time it takes the user to have a CSA pick up the chat. You should probably use the same method as in [chat-avg-waiting-time.sql](https://github.com/buerokratt/Analytics-Module/pull/41/files#diff-f92c0147e049156c1fad759ba3b3a6254b36b4ed9a0811ecf019dd627af73242)

2023-01-30 11:45 UTC, gdrui commented on DSL/Resql/chat-cif-all-csas-away.sql
> +    AND message.event = 'contact-information-fulfilled'
Correct me if I'm wrong but `contact-information-fulfilled` should only be an event fired when the end-user has left their contact information in response to such a request. Currently it looks like when the bot tries to actually get a CSA to take over, it will first unassign itself, so there will be an update to the chat table to remove the bot from the CSA ID field.

2023-02-02 01:51 UTC, baha-a commented on DSL/Resql/chat-cif-all-csas-away.sql
> +AND csa.status = 'AWAY'
Fixed.

2023-02-02 01:51 UTC, baha-a commented on DSL/Resql/chat-cif-long-waiting-time.sql
> +            MIN(created) FILTER (WHERE event = 'contact-information-fulfilled')
Done.

2023-02-02 01:52 UTC, baha-a commented on DSL/Resql/chat-cif-all-csas-away.sql
> +    AND message.event = 'contact-information-fulfilled'
I've changed the logic here, please have a look at it again.

2023-02-03 10:59 UTC, gdrui requested changes

2023-02-03 10:59 UTC, gdrui commented on DSL/Resql/chat-cif-all-csas-away.sql
> +AND csa.status = 'AWAY'
right now this checks only if CSA went away at any point during the chat, but I think you also need to check if the CSA was already away before the chat began?

2023-02-03 10:59 UTC, gdrui commented on DSL/Resql/chat-cif-all-csas-away.sql
> +	AND customer_support_id <> (SELECT name FROM botname)
I dont think it is a requirement that the user also didnt have any communication with the bot. Since CSAs are all away I would assume they would only be able to talk to the bot.

2023-02-16 11:05 UTC, baha-a commented on DSL/Resql/chat-cif-all-csas-away.sql
> +AND csa.status = 'AWAY'
Fixed in [PR #52](https://github.com/buerokratt/Analytics-Module/pull/52), [here](https://github.com/buerokratt/Analytics-Module/pull/52/files#diff-d145130705fa0752158846a7e4e48f88d7c569daae2d4680545c32b95fc75ec6)

2023-02-17 11:28 UTC, baha-a commented
Closed in favor of [PR#52](https://github.com/buerokratt/Analytics-Module/pull/52).

2023-02-17 11:28 UTC, closed without merging