10-metrics-and-graphics-under-menu-button-nõustajad-csas
buerokratt/Analytics-Module pull request #42
Opened 2023-01-27 11:45 UTC by 1AhmedYasser

2023-01-30 12:12 UTC, gdrui requested changes

2023-01-30 12:12 UTC, gdrui commented on DSL/Resql/csa-chat-forwards.sql
> +  (SELECT COALESCE (f_chats.date_time,
coalesce takes in any number of arguments so you can remove this nested coalescing

2023-01-30 12:12 UTC, gdrui commented on DSL/Resql/get-chat-count-csa.sql
> +       AND message.author_role = 'end-user' )
is this query supposed to return a single number, not a series to be shown in a chart?

2023-02-01 23:53 UTC, 1AhmedYasser commented on DSL/Resql/csa-chat-forwards.sql
> +          AND forwarded_to <> (
ok, i am on board with checking that the `received_from` is not the bot, but regarding the forward to & recovered from being with the same result, i find it confusing since a chat can be only forwarded or only received or both, am i missing something

2023-02-13 20:32 UTC, baha-a approved these changes

2023-02-21 07:06 UTC, merged