22-data-mapper-dsl-to-generate-csv
buerokratt/Analytics-Module pull request #45
Opened 2023-01-31 11:55 UTC by 1AhmedYasser

2023-02-01 12:28 UTC, gdrui requested changes

2023-02-01 12:28 UTC, gdrui commented on docker-compose.yml
> +      - ./DSL/DMapper/hbs:/workspace/app/views/my/restful/url
`my/restful/url` is presumably a placeholder here, we can perhaps keep our stuff in a folder called `analytics` instead, so that the datamapper request urls would be `http://data_mapper:3000/analytics/get-csv`

If both JS and HBS files have the same name, how does DMapper know which to use when handling the query?

2023-02-01 12:28 UTC, gdrui commented on GUI/package.json
> +    "start": "PORT=3001 react-scripts start",
it would be cleaner to set this env variable in the environment section of docker-compose

2023-02-01 12:40 UTC, gdrui commented on DSL/DMapper/hbs/get-csv.handlebars
> +{{#each this}}{{#if ../../qul}}{{../../qul}}{{this}}{{../../qul}} {{/if}}{{#unless ../../qul}}{{this}}{{/unless}}{{#unless @last}}{{#if ../../del}}{{../../del}}{{/if}}{{#unless ../../del}},{{/unless}
instead of `../qul `or `../../qul ` you can always access the root context the same way everywhere by using `@root.qul`

2023-02-01 22:00 UTC, baha-a requested changes

2023-02-01 22:37 UTC, 1AhmedYasser commented on docker-compose.yml
> +      - ./DSL/DMapper/hbs:/workspace/app/views/my/restful/url
Data Mapper Directs HBS to `views/my/restful/url` & JS to `js/my/restful/url` as documented in data mapper, so i guess we could use it like `http://data_mapper:3000/hbs/analytics/get-csv` & `http://data_mapper:3000/js/analytics/get-csv`

2023-02-02 11:33 UTC, gdrui requested changes

2023-02-02 11:33 UTC, gdrui commented on docker-compose.yml
> +      - ./DSL/DMapper/hbs:/workspace/app/views/my/restful/url
The URL is composed of the folders where you place it in, so right now you are placing everything in my/restful/url which would mean we would have to use `http://data_mapper:3000/my/restful/url/get-csv`. Instead of this you should map the volume so that we would have the desired URL, by doing 
`- ./DSL/DMapper/hbs:/workspace/app/views/analytics`

2023-02-03 10:50 UTC, baha-a approved these changes

2023-02-03 10:51 UTC, gdrui approved these changes

2023-02-03 14:25 UTC, merged