9 metrics and charts under menu button tagasiside feedback
buerokratt/Analytics-Module pull request #50
Opened 2023-02-10 07:52 UTC by 1AhmedYasser

2023-02-13 09:41 UTC, gdrui requested changes

2023-02-13 09:41 UTC, gdrui commented on GUI/src/components/Dropdown/index.tsx
> +export default DropDown
This component is not required I think, we already have a component <FormSelect> with the correct styling

2023-02-13 09:41 UTC, gdrui commented on GUI/src/components/FormElements/FormCheckbox/FormCheckbox.scss
>          }
are these changes absolutely necessary? This is a CVI component and should be compatible when the CVI gets separated in the future

2023-02-13 09:41 UTC, gdrui commented on GUI/src/components/MetricsCharts/index.tsx
> +  const charts = ['Tulpdiagramm', 'Sektordiagramm', 'joondiagramm']
the actual display values should be translated fields and should be separate from the values. for example these could be

```
type ChartType = {
  name: string
  value: string
}

const charts: ChartType[] = [
  {
    name: 'chart.columnChart',
    value: 'columnChart'
  },
  ...
]
```

2023-02-13 09:41 UTC, gdrui commented on GUI/src/components/MetricsCharts/index.tsx
> +              downloadCSV(data.chartData)
this should guard against double clicks while the request is already in flight

2023-02-13 09:41 UTC, gdrui commented on GUI/src/components/Track/index.tsx
> +  isFlex?: boolean;
are these changes absolutely necessary? This is a CVI component which is something better left untouched (unless theres a really good reason)

For example if you need to to not be a flex, why use a Track at all, since thats what it seems to be for? You could just use a regular <div>

2023-02-13 09:59 UTC, 1AhmedYasser commented on GUI/src/components/Track/index.tsx
> +  isFlex?: boolean;
I Guess here i want to give an extra option to the track without affecting its normal behavior, so i can use flex & make use of all other features & style that track provides, so i just extended it. what do you think ?

2023-02-13 11:56 UTC, gdrui approved these changes
LGTM

2023-02-13 12:19 UTC, baha-a requested changes

2023-02-13 12:27 UTC, baha-a requested changes

2023-02-13 12:27 UTC, baha-a commented on GUI/src/pages/FeedbackPage.tsx
> +  }, [currentConfigs])
I think it's better to add only `currentConfigs?.metric` to the dependency array, otherwise this 'useEffect' will fire every time `currentConfigs` changes.

```js
useEffect(()=>{
// the same code
}, [currentConfigs?.metric])
```

2023-02-13 15:53 UTC, 1AhmedYasser commented on GUI/src/pages/ReportsPage.tsx
> +        ></OptionsPanel>
This is related to the reports PR, will be fixed there to avoid conflict

2023-02-13 18:10 UTC, 1AhmedYasser commented on GUI/src/pages/FeedbackPage.tsx
> +  }, [currentConfigs])
This Wont work as if you change the time then the current configs.metric won't be updated so you wont actually call any api's on the period change

2023-02-13 18:25 UTC, 1AhmedYasser commented on GUI/src/components/MetricAndPeriodOptions/MetricOptionsGroup/index.tsx
> +              style={{ marginRight: '.5rem', marginBottom :'.3rem',  marginTop :'.3rem'}}
Currently the Button CVI  Compnenet has its own style and i just appended these 3, if i were to seperate this into styles.scss, it would actually remove the current Button sytling and i would have to put everything again in it, what do you think ?

2023-02-13 20:31 UTC, baha-a approved these changes

2023-02-13 23:19 UTC, gdrui requested changes

2023-02-13 23:19 UTC, gdrui commented on GUI/src/pages/FeedbackPage.tsx
> +      .subscribe((configs: any) => setConfigs(configs))
This doesn't fix the race condition though, it just hides it. You should switchMap to the actual fetch and set the result of the fetch in subscribe. Something like this, but you also have to modify the fetch functions so they wont setChartData on their own but return the chartData instead. I haven't tested this myself, but this would be the way

```javascript
const subscription = configsSubject
  .pipe(
    distinctUntilChanged(),
    debounceTime(300),
    switchMap((config) => {
      switch (config.metric) {
        case 'statuses':
          return fetchChatsStatuses()
        case 'burokratt_chats':
          return fetchAverageFeedbackOnBuerokrattChats()
        case 'advisor_chats':
          return fetchNpsOnCSAChatsFeedback()
        case 'selected_advisor_chats':
          return fetchNpsOnSelectedCSAChatsFeedback()
        case 'negative_feedback':
          return fetchChatsWithNegativeFeedback()
      }
    }),
  )
  .subscribe((chartData: any) => setChartData(chartData))
```

2023-02-13 23:19 UTC, gdrui commented on GUI/src/pages/FeedbackPage.tsx
> +    setChartKey('dateTime')
It looks like the only valid value for all of these is dateTime, so no need to set it and keep it as a state variable, just a regular const would do

2023-02-14 07:28 UTC, gdrui approved these changes

2023-02-14 08:10 UTC, merged