3 publish data in open data portal
buerokratt/Analytics-Module pull request #53
Opened 2023-02-16 21:08 UTC by gdrui

2023-02-17 09:27 UTC, 1AhmedYasser requested changes

2023-02-17 09:27 UTC, 1AhmedYasser commented on GUI/src/pages/ReportsPage.tsx
> +              onClick={() => setDatasetCreationVisible(true)}
As shown in the demo, please make sure to clear any previous data in the fields when you click on create new data set

2023-02-17 09:49 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/odp/update-scheduled-report.yml
> +
Please Remove Extra Empty Lines

2023-02-17 09:50 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/odp/upload.yml
> +#upload:
is it a refernece for uploading to organization ? or its not needed ?

2023-02-17 10:16 UTC, gdrui commented on GUI/src/pages/ReportsPage.tsx
> +              onClick={() => setDatasetCreationVisible(true)}
Creating a dataset doesn't have this issue, it either starts with empty fields or it loads the fields you have selected earlier when editing an existing dataset. 

This issue did appear with the API settings form though, but I wonder if it might actually be a useful thing since the user will need to update the API key but might want to keep the existing organisation ID? If you disagree I could fix it for that form

2023-02-17 10:19 UTC, gdrui commented on DSL/Ruuter/POST/odp/upload.yml
> +#upload:
It is needed and should be uncommented once Ruuter supports file uploads and variables in URLs. Currently Ruuter will not run when we leave this uncommented, because it uses these unknown options.

I've also commented in other places where the URL should be replaced once Ruuter supports these things and I've made mock requests to some places where possible

2023-02-17 10:19 UTC, 1AhmedYasser commented on GUI/src/pages/ReportsPage.tsx
> +              onClick={() => setDatasetCreationVisible(true)}
Well, i guess you have a point. But in UI wise it always should be empty on first open. like a a sign up page, every time you click it, it should empty all the fields. You could have earlier data as suggesstions for the user if you like

2023-02-17 10:22 UTC, 1AhmedYasser commented on DSL/Ruuter/POST/odp/upload.yml
> +#upload:
Noted

2023-02-17 10:42 UTC, 1AhmedYasser commented on GUI/src/pages/ReportsPage.tsx
> +              onClick={() => setDatasetCreationVisible(true)}
But i guess its not an issue per-say, its just UI enhancment

2023-02-17 10:42 UTC, 1AhmedYasser approved these changes

2023-02-17 10:48 UTC, gdrui commented on GUI/src/pages/ReportsPage.tsx
> +              onClick={() => setDatasetCreationVisible(true)}
Implemented a form reset when the drawer visibility changes

2023-02-17 10:51 UTC, 1AhmedYasser approved these changes

2023-02-17 13:55 UTC, baha-a requested changes

2023-02-17 13:55 UTC, baha-a commented on GUI/src/types/reports.ts
> +  }[]
This can be simplifiled as such:

```ts

export type ODPValuesType = {
  id: string
  name: string
}

export type ODPValues = {
  keywords: ODPValuesType[]
  categories: ODPValuesType[]
  regions: ODPValuesType[]
  licences: ODPValuesType[]
}

```

2023-02-17 13:55 UTC, baha-a commented on DSL/Resql/get-period-times.sql
> +        WHEN (:period = 'year') THEN date_trunc('year', NOW()) - INTERVAL '1 day'
All these lines end with `INTERVAL '1 day'` is this correct? the previous `CASE` statement end with values like `1 week`, `1 month`, ... etc.
Could you make sure the brackets are correct here as well?

2023-02-17 14:19 UTC, gdrui commented on DSL/Resql/get-period-times.sql
> +        WHEN (:period = 'year') THEN date_trunc('year', NOW()) - INTERVAL '1 day'
This one is correct yes, I subtract 1 day to get the last day of the previous period. 

So if the period is a 'week', `start` would be `date_trunc('week', NOW() - INTERVAL '1 week')` which is the Monday of the previous week, and `end` would be `date_trunc('week', NOW()) - INTERVAL '1 day'` so the Sunday of the previous week. Since BETWEEN is inclusive of the last date, it will give the correct input as start: last week's Monday, end: last week's Sunday.

2023-02-17 14:34 UTC, gdrui commented on GUI/src/types/reports.ts
> +  }[]
Good point, fixed

2023-02-17 14:42 UTC, baha-a commented on DSL/Resql/get-period-times.sql
> +        WHEN (:period = 'year') THEN date_trunc('year', NOW()) - INTERVAL '1 day'
I see, it make sense now.

2023-02-17 14:42 UTC, baha-a approved these changes

2023-02-20 08:25 UTC, turnerrainer commented
I'll merge it as it is at the moment but please have separate pull requests for separate issues. Hard to keep track of things is different business goals and technical solutions are within the same PR.

2023-02-20 08:25 UTC, merged